/* Generated By:JavaCC: Do not edit this line. GuardExpressionParserConstants.java */
package dk.aau.cs.model.CPN.GuardExpressionParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GuardExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 1;
  /** RegularExpression Id. */
  int AND = 2;
  /** RegularExpression Id. */
  int NOT = 3;
  /** RegularExpression Id. */
  int LOGOP = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int SUB = 6;
  /** RegularExpression Id. */
  int MULT = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int IDENT = 9;
  /** RegularExpression Id. */
  int OP = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OR>",
    "<AND>",
    "<NOT>",
    "<LOGOP>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<NUM>",
    "<IDENT>",
    "<OP>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"++\"",
    "\"--\"",
  };

}
