package net.tapaal.gui.petrinet.verification;

public enum EngineFeature {
    FASTEST_TRACE,
    DEADLOCK_NET_DEGREE_2_EXP,
    DEADLOCK_EG_OR_AF,
    DEADLOCK_WITH_INHIB,
    WEIGHTS,
    INHIBITOR_ARCS,
    COLORED_INHIBITOR_ARCS,
    URGENT_TRANSITIONS,
    EG_OR_AF,
    STRICT_NETS,
    TIMED_NETS,
    DEADLOCK_NET_DEGREE_GREATER_THAN_2,
    GAMES,
    EG_OR_AF_WITH_NET_DEGREE_GREATER_THAN_2,
    NESTED_QUANTIFICATIONS,
    COLORED,
    ONLY_UNTIMED,
    SMC,
    COLORED_PLACE_QUERIES,
    NONZERO_INITIAL_TOKEN_AGES
}
