#!/bin/bash 
##Overwrite verifyta path:
#verifyta=/path/to/verifyta

if [ -z "$verifyta" ]; then
	#Search path for verifyta
	export verifyta=`which verifyta`
fi

echo $0
( cd `dirname "$0"`; export verifytapn=$PWD/lib/verifytapn; cd lib; java -cp ./:* TAPAAL )
