/* Generated By:JavaCC: Do not edit this line. SUMOQueryParserConstants.java */
package dk.aau.cs.TCTL.SUMOParsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SUMOQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 1;
  /** RegularExpression Id. */
  int FALSE = 2;
  /** RegularExpression Id. */
  int DEADLOCK = 3;
  /** RegularExpression Id. */
  int EF = 4;
  /** RegularExpression Id. */
  int EG = 5;
  /** RegularExpression Id. */
  int AF = 6;
  /** RegularExpression Id. */
  int AG = 7;
  /** RegularExpression Id. */
  int I = 8;
  /** RegularExpression Id. */
  int N = 9;
  /** RegularExpression Id. */
  int P = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int XOR = 14;
  /** RegularExpression Id. */
  int IMPL = 15;
  /** RegularExpression Id. */
  int BIIMPL = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MULT = 18;
  /** RegularExpression Id. */
  int QUOTE = 19;
  /** RegularExpression Id. */
  int ENDQUOTE = 20;
  /** RegularExpression Id. */
  int IDENT = 21;
  /** RegularExpression Id. */
  int NUM = 22;
  /** RegularExpression Id. */
  int OP = 23;
  /** RegularExpression Id. */
  int NOP = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TRUE>",
    "<FALSE>",
    "<DEADLOCK>",
    "<EF>",
    "<EG>",
    "<AF>",
    "<AG>",
    "\"I\"",
    "\"N\"",
    "\"P\"",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"xor\"",
    "\"=>\"",
    "\"<=>\"",
    "<PLUS>",
    "\"*\"",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<IDENT>",
    "<NUM>",
    "<OP>",
    "\"!=\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"#tokens(\"",
    "\",\"",
  };

}
