options {
    LOOKAHEAD = 1;
    CHOICE_AMBIGUITY_CHECK = 2;
    OTHER_AMBIGUITY_CHECK = 1;
    STATIC = false;
    DEBUG_PARSER = false;
    DEBUG_LOOKAHEAD = false;
    DEBUG_TOKEN_MANAGER = false;
    ERROR_REPORTING = true;
    JAVA_UNICODE_ESCAPE = false;
    UNICODE_INPUT = false;
    IGNORE_CASE = false;
    USER_TOKEN_MANAGER = false;
    USER_CHAR_STREAM = false;
    BUILD_PARSER = true;
    BUILD_TOKEN_MANAGER = true;
    SANITY_CHECK = true;
    }

    PARSER_BEGIN(TAPAALLTLQueryParser)

    package dk.aau.cs.TCTL.LTLParsing;

import java.io.StringReader;
import java.util.ArrayList;

import dk.aau.cs.TCTL.*;

public class TAPAALLTLQueryParser {

    private static final String ERROR_PARSING_QUERY_MESSAGE = "TAPAAL countered an error trying to parse the query";

    public static TCTLAbstractPathProperty parse(String query) throws ParseException {
        TAPAALLTLQueryParser parser = new TAPAALLTLQueryParser(new StringReader(query));
        return parser.Start();
    }

    private static TCTLAbstractStateProperty wrapPathToState(TCTLAbstractProperty property) {
        if (property instanceof TCTLAbstractStateProperty) {
            return (TCTLAbstractStateProperty) property;
        } else if (property instanceof TCTLAbstractPathProperty) {
            return new TCTLPathToStateConverter((TCTLAbstractPathProperty)property);
        }
        
        return null;
    }

    private static TCTLAbstractPathProperty wrapStateToPath(TCTLAbstractProperty property) {
        if (property instanceof TCTLAbstractPathProperty) {
            return (TCTLAbstractPathProperty) property;
        } else if (property instanceof TCTLAbstractStateProperty) {
            return new TCTLStateToPathConverter((TCTLAbstractStateProperty)property);
        }

        return null;
    }
}

    PARSER_END(TAPAALLTLQueryParser)

TOKEN :
    {
<TRUE: "true" | "TRUE">
    |
<FALSE: "false" | "FALSE">
    }

    TOKEN :
    {
<A: "A">
    |
<E: "E">
    |
<U: "U">
    |
<F: "F">
    |
<G: "G">
    |
<X: "X">
    }

    TOKEN :
    {
<OR: "or" | "||">
    |
<AND: "and" | "&&">
    |
<NOT: "not" | "!">
    }

    TOKEN :
    {
<PLUS: "+">
    |
<MINUS: "-">
    |
<MULT: "*">
    }

    TOKEN :
    {
< NUM: ("-")? ( ["0"-"9"] )+ >
    |
<IDENT: ["a"-"z","A"-"Z","_"] ( ["a"-"z","A"-"Z","_","0"-"9"] )* >
    }

    TOKEN :
    {
<OP: "<" | "!=" | "<=" | ">" | "=" | "==" | ">=" | ">" >
    }

    SKIP :
    {
    " "
    | "\t"
    | "\n"
    | "\r"
    }

/** Root production. */
TCTLAbstractPathProperty Start() :
{
        TCTLAbstractPathProperty child = null;
}
{
   child = AbstractPathProperty() <EOF> {return child; }
}

TCTLAbstractPathProperty AbstractPathProperty() :
{
        TCTLAbstractProperty child = null;
}
{
    <A> child = LTLFormula() {return new LTLANode(wrapPathToState(child)); }
    | <E> child = LTLFormula() {return new LTLENode(wrapPathToState(child)); }
}

TCTLAbstractProperty LTLFormula() :
{
    TCTLAbstractProperty child = null;
}
{
    child = OrExpr() { return child; }
}

TCTLAbstractProperty OrExpr() :
{
    TCTLAbstractProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> disjunctions = new ArrayList<TCTLAbstractStateProperty>();
}
{
    currentChild = AndExpr()
    { disjunctions.add(wrapPathToState(currentChild)); }
    (
    <OR> currentChild = AndExpr()
    { disjunctions.add(wrapPathToState(currentChild)); }
    )*
    { return disjunctions.size() == 1 ? currentChild : new TCTLOrListNode(disjunctions); }
}

TCTLAbstractProperty AndExpr() :
{
    TCTLAbstractProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> conjunctions = new ArrayList<TCTLAbstractStateProperty>();
}
{
    currentChild = UntilExpr()
    { conjunctions.add(wrapPathToState(currentChild)); }
    (
    <AND> currentChild = UntilExpr()
    { conjunctions.add(wrapPathToState(currentChild)); }
    )*
    { return conjunctions.size() == 1 ? currentChild : new TCTLAndListNode(conjunctions); }
}

TCTLAbstractProperty UntilExpr() :
{
    TCTLAbstractProperty left;
    TCTLAbstractProperty right = null;
}
{
    left = UnaryExpr()
    [
        LOOKAHEAD(2) <U> right = UntilExpr()
    ]
    { return (right == null ? left : new LTLUNode(wrapPathToState(left), wrapPathToState(right))); }
}

TCTLAbstractProperty UnaryExpr() :
{
    TCTLAbstractProperty child;
}
{
    <NOT> child = UnaryExpr() { return new TCTLNotNode(wrapPathToState(child)); }
    | <F> child = UnaryExpr() { return new LTLFNode(wrapPathToState(child)); }
    | <G> child = UnaryExpr() { return new LTLGNode(wrapPathToState(child)); }
    | <X> child = UnaryExpr() { return new LTLXNode(wrapPathToState(child)); }
    | child = Factor() { return child; }
}

TCTLAbstractProperty Factor() :
{
    TCTLAbstractProperty thisProp;
    Token temp = null;
    Token transition;
}
{
    (
      <TRUE> {thisProp = new TCTLTrueNode(); }
    | <FALSE> {thisProp = new TCTLFalseNode(); }
    | LOOKAHEAD(AtomicProposition())
      thisProp = AtomicProposition()
    | [ LOOKAHEAD(2) temp = <IDENT> "." ] transition = <IDENT> {
      thisProp = new TCTLTransitionNode(temp == null ? "" : temp.image, transition.image); }
    | "(" thisProp = OrExpr() ")"
    )
    { return thisProp; }
}

TCTLAbstractStateProperty AtomicProposition() :
{
    TCTLAbstractStateProperty left;
    TCTLAbstractStateProperty right;
    Token op;
}
{
    (
    left = AritmeticExpr() op = <OP> right = AritmeticExpr()
    )
    {
    return new TCTLAtomicPropositionNode(left, op.image, right);
    }
}

TCTLAbstractStateProperty AritmeticExpr() :
{
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> terms = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
}
{
    currentChild = AritmeticMinusExpr()
    { terms.add(currentChild); }
    (
    op = <PLUS> currentChild = AritmeticMinusExpr()
    {
    terms.add(new AritmeticOperator(op.image));
    terms.add(currentChild);
    }
    )*
    { return terms.size() == 1 ? currentChild : new TCTLTermListNode(terms); }
}

TCTLAbstractStateProperty AritmeticMinusExpr() :
{
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> terms = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
}
{
    currentChild = AritmeticTerm()
    { terms.add(currentChild); }
    (
    op = <MINUS> currentChild = AritmeticTerm()
    {
    terms.add(new AritmeticOperator(op.image));
    terms.add(currentChild);
    }
    )*
    { return terms.size() == 1 ? currentChild : new TCTLTermListNode(terms); }
}

TCTLAbstractStateProperty AritmeticTerm() :
{
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> factors = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
}
{
    currentChild = AritmeticFactor()
    { factors.add(currentChild); }
    (
    op = <MULT> currentChild = AritmeticFactor()
    {
    factors.add(new AritmeticOperator(op.image));
    factors.add(currentChild);
    }
    )*
    { return factors.size() == 1 ? currentChild : new TCTLTermListNode(factors); }
}

TCTLAbstractStateProperty AritmeticFactor() :
{
TCTLAbstractStateProperty thisProp;
    Token temp = null;
    Token place;
	String color = null;
    Token op;
    Token num;
}
{
    (
    [ LOOKAHEAD(2) temp = <IDENT> "." ] place = <IDENT> [ "." color = QueryColor() ] { thisProp = TCTLPlaceNode.fromManualQuery(temp == null ? "" : temp.image, place.image, color); }
    | num = <NUM> { thisProp = new TCTLConstNode(Integer.parseInt(num.image)); }
    | "(" thisProp = AritmeticExpr() ")"
    )

    { return thisProp; }
}

String QueryColor() :
{
    Token color;
    ArrayList<String> tuple = new ArrayList<>();
}
{
    (
        color = <IDENT> { return color.image; }
        | color = <NUM> { return color.image; }
        | "(" color = QueryColorPart() { tuple.add(color.image); }
            ("," color = QueryColorPart() { tuple.add(color.image); })* ")"
            { return "(" + String.join(", ", tuple) + ")"; }
    )
}

Token QueryColorPart() :
{
    Token color;
}
{
    (color = <IDENT> | color = <NUM>) { return color; }
}
