
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 20 11:13:57 GMT+01:00 2007
//----------------------------------------------------

package expressions;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int AND = 15;
  public static final int LT = 9;
  public static final int NE = 14;
  public static final int PLUS = 2;
  public static final int OR = 16;
  public static final int RPAREN = 8;
  public static final int NOT = 17;
  public static final int TRUE = 18;
  public static final int LPAREN = 7;
  public static final int GT = 10;
  public static final int LE = 11;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int FALSE = 19;
  public static final int GE = 12;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int VAR = 21;
  public static final int POWER = 6;
}

