/* Generated By:JavaCC: Do not edit this line. TAPAALLTLQueryParserConstants.java */
package dk.aau.cs.TCTL.LTLParsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TAPAALLTLQueryParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int TRUE = 1;
    /** RegularExpression Id. */
    int FALSE = 2;
    /** RegularExpression Id. */
    int DEADLOCK = 3;
    /** RegularExpression Id. */
    int A = 4;
    /** RegularExpression Id. */
    int U = 5;
    /** RegularExpression Id. */
    int F = 6;
    /** RegularExpression Id. */
    int G = 7;
    /** RegularExpression Id. */
    int X = 8;
    /** RegularExpression Id. */
    int OR = 9;
    /** RegularExpression Id. */
    int AND = 10;
    /** RegularExpression Id. */
    int NOT = 11;
    /** RegularExpression Id. */
    int PLUS = 12;
    /** RegularExpression Id. */
    int MINUS = 13;
    /** RegularExpression Id. */
    int MULT = 14;
    /** RegularExpression Id. */
    int NUM = 15;
    /** RegularExpression Id. */
    int IDENT = 16;
    /** RegularExpression Id. */
    int OP = 17;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = {
        "<EOF>",
        "<TRUE>",
        "<FALSE>",
        "<DEADLOCK>",
        "\"A\"",
        "\"U\"",
        "\"F\"",
        "\"G\"",
        "\"X\"",
        "<OR>",
        "<AND>",
        "<NOT>",
        "\"+\"",
        "\"-\"",
        "\"*\"",
        "<NUM>",
        "<IDENT>",
        "<OP>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"(\"",
        "\")\"",
        "\".\"",
    };

}
