options {
    LOOKAHEAD = 1;
    CHOICE_AMBIGUITY_CHECK = 2;
    OTHER_AMBIGUITY_CHECK = 1;
    STATIC = false;
    DEBUG_PARSER = false;
    DEBUG_LOOKAHEAD = false;
    DEBUG_TOKEN_MANAGER = false;
    ERROR_REPORTING = true;
    JAVA_UNICODE_ESCAPE = false;
    UNICODE_INPUT = false;
    IGNORE_CASE = false;
    USER_TOKEN_MANAGER = false;
    USER_CHAR_STREAM = false;
    BUILD_PARSER = true;
    BUILD_TOKEN_MANAGER = true;
    SANITY_CHECK = true;
    }

    PARSER_BEGIN(TAPAALHyperLTLQueryParser)

    package dk.aau.cs.TCTL.HyperLTLParsing;

import java.io.StringReader;
import java.util.ArrayList;

import dk.aau.cs.TCTL.*;

public class TAPAALHyperLTLQueryParser {

    private static final String ERROR_PARSING_QUERY_MESSAGE = "TAPAAL countered an error trying to parse the query";

    public static TCTLAbstractPathProperty parse(String query) throws ParseException {
        TAPAALHyperLTLQueryParser parser = new TAPAALHyperLTLQueryParser(new StringReader(query));
        return parser.Start();
    }

    private static TCTLAbstractStateProperty wrapPathToState(TCTLAbstractProperty property) {
        if (property instanceof TCTLAbstractStateProperty) {
            return (TCTLAbstractStateProperty) property;
        } else if (property instanceof TCTLAbstractPathProperty) {
            return new TCTLPathToStateConverter((TCTLAbstractPathProperty)property);
        }
        
        return null;
    }

    private static TCTLAbstractPathProperty wrapStateToPath(TCTLAbstractProperty property) {
        if (property instanceof TCTLAbstractPathProperty) {
            return (TCTLAbstractPathProperty) property;
        } else if (property instanceof TCTLAbstractStateProperty) {
            return new TCTLStateToPathConverter((TCTLAbstractStateProperty)property);
        }

        return null;
    }
}

    PARSER_END(TAPAALHyperLTLQueryParser)

TOKEN :
    {
<TRUE: "true" | "TRUE">
    |
<FALSE: "false" | "FALSE">
    }

    TOKEN :
    {
<A: "A">
    |
<E: "E">
    |
<U: "U">
    |
<F: "F">
    |
<G: "G">
    |
<X: "X">
    }

    TOKEN :
    {
<OR: "or" | "||">
    |
<AND: "and" | "&&">
    |
<NOT: "not" | "!">
    }

    TOKEN :
    {
<PLUS: "+">
    |
<MINUS: "-">
    |
<MULT: "*">
    }

    TOKEN :
    {
< NUM: ("-")? ( ["0"-"9"] )+ >
    |
<IDENT: ["a"-"z","A"-"Z","_"] ( ["a"-"z","A"-"Z","_","0"-"9"] )* >
    }

    TOKEN :
    {
<OP: "<" | "!=" | "<=" | ">" | "=" | "==" | ">=" | ">" >
    }

    SKIP :
    {
    " "
    | "\t"
    | "\n"
    | "\r"
    }

/** Root production. */
TCTLAbstractPathProperty Start() :
{
        TCTLAbstractPathProperty child = null;
}
{
   child = AbstractPathProperty() <EOF> {return child; }
}

TCTLAbstractPathProperty AbstractPathProperty() :
{
        TCTLAbstractPathProperty pathChild = null;
}
{
    pathChild = AllPathProperty() {return pathChild;}
    | pathChild = ExistsPathProperty() {return pathChild;}
}

TCTLAbstractPathProperty AllPathProperty() :
{
        TCTLAbstractProperty pathChild = null;
        Token trace;
}
{
    <A> trace = <IDENT> "(" pathChild = ParanthesesExpr() ")" {return new LTLANode(wrapPathToState(pathChild), trace.image); }
}

TCTLAbstractPathProperty ExistsPathProperty() :
{
        TCTLAbstractProperty pathChild = null;
        Token trace;
}
{
    <E> trace = <IDENT> "(" pathChild = ParanthesesExpr() ")" {return new LTLENode(wrapPathToState(pathChild), trace.image); }
}

TCTLAbstractProperty ParanthesesExpr() :
{
    TCTLAbstractProperty pathChild = null;
}
{
    LOOKAHEAD(AbstractPathProperty()) pathChild = AbstractPathProperty() {return pathChild;}
    | LOOKAHEAD(2) "(" pathChild = AbstractPathProperty() ")" {return pathChild;}
    | pathChild = OrExpr() {return pathChild; }
}

TCTLAbstractProperty OrExpr() :
{
    TCTLAbstractProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> disjunctions = new ArrayList<TCTLAbstractStateProperty>();
}
{
    currentChild = AndExpr()
    { disjunctions.add(wrapPathToState(currentChild)); }
    (
    <OR> currentChild = AndExpr()
    { disjunctions.add(wrapPathToState(currentChild)); }
    )*
    { return disjunctions.size() == 1 ? currentChild : new TCTLOrListNode(disjunctions); }
}

TCTLAbstractProperty AndExpr() :
{
    TCTLAbstractProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> conjunctions = new ArrayList<TCTLAbstractStateProperty>();
}
{
    currentChild = UntilExpr()
    { conjunctions.add(wrapPathToState(currentChild)); }
    (
    <AND> currentChild = UntilExpr()
    { conjunctions.add(wrapPathToState(currentChild)); }
    )*
    { return conjunctions.size() == 1 ? currentChild : new TCTLAndListNode(conjunctions); }
}

TCTLAbstractProperty UntilExpr() :
{
    TCTLAbstractProperty left;
    TCTLAbstractProperty right = null;
}
{
    left = UnaryExpr()
    [
        LOOKAHEAD(2) <U> right = UntilExpr()
    ]
    { return (right == null ? left : new LTLUNode(wrapPathToState(left), wrapPathToState(right))); }
}

TCTLAbstractProperty UnaryExpr() :
{
    TCTLAbstractProperty child;
}
{
    <NOT> child = UnaryExpr() { return new TCTLNotNode(wrapPathToState(child)); }
    | <F> child = UnaryExpr() { return new LTLFNode(wrapPathToState(child)); }
    | <G> child = UnaryExpr() { return new LTLGNode(wrapPathToState(child)); }
    | <X> child = UnaryExpr() { return new LTLXNode(wrapPathToState(child)); }
    | child = Factor() { return child; }
}

TCTLAbstractProperty Factor() :
{
    TCTLAbstractProperty thisProp;
    Token temp = null;
    Token transition = null;
    Token trace = null;
}
{
    (
    <TRUE> {thisProp = new TCTLTrueNode(); }
    | <FALSE> {thisProp = new TCTLFalseNode(); }
    | LOOKAHEAD(AtomicProposition()) thisProp = AtomicProposition()
    | LOOKAHEAD(PathScope()) thisProp = PathScope()
    | "(" thisProp = OrExpr() ")"
    )
    { return thisProp; }
}

TCTLAbstractStateProperty PathScope() :
{
    TCTLAbstractStateProperty stateChild = null;
    Token trace = null;
}
{
    trace = <IDENT> "." stateChild = TransitionExpr() {return new HyperLTLPathScopeNode(stateChild, trace.image); }
}


TCTLAbstractStateProperty TransitionExpr() :
{
    TCTLAbstractStateProperty stateChild = null;
    Token temp = null;
    Token transition;
}
{
    temp = <IDENT> "." transition = <IDENT> {return new TCTLTransitionNode(temp == null ? "" : temp.image, transition.image); }
}

TCTLAbstractStateProperty AtomicProposition() :
{
TCTLAbstractStateProperty left = null;
TCTLAbstractStateProperty right = null;
String operator;
Token op;
}
{
    (
    left = AritmeticExpr() op = <OP> right = AritmeticExpr()
    )
    {
        operator = op.image;
        if(operator.equals("==")) operator = "=";
        return new TCTLAtomicPropositionNode(left, operator, right);
    }
}

TCTLAbstractStateProperty AritmeticExpr() :
    {
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> terms = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
    }
{
    currentChild = AritmeticMinusExpr()
    { terms.add(currentChild); }
    (
    op = <PLUS> currentChild = AritmeticMinusExpr()
    {
    terms.add(new AritmeticOperator(op.image));
    terms.add(currentChild);
    }
    )*
    { return terms.size() == 1 ? currentChild : new TCTLTermListNode(terms); }
}


TCTLAbstractStateProperty AritmeticMinusExpr() :
    {
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> terms = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
    }
{
    currentChild = AritmeticTerm()
    { terms.add(currentChild); }
    (
    op = <MINUS> currentChild = AritmeticTerm()
    {
    terms.add(new AritmeticOperator(op.image));
    terms.add(currentChild);
    }
    )*
    { return terms.size() == 1 ? currentChild : new TCTLTermListNode(terms); }
}

TCTLAbstractStateProperty AritmeticTerm() :
{
    TCTLAbstractStateProperty currentChild;
    ArrayList<TCTLAbstractStateProperty> factors = new ArrayList<TCTLAbstractStateProperty>();
    Token op;
}
{
    currentChild = AritmeticFactor()
    { factors.add(currentChild); }
    (
    op = <MULT> currentChild = AritmeticFactor()
    {
    factors.add(new AritmeticOperator(op.image));
    factors.add(currentChild);
    }
    )*
    { return factors.size() == 1 ? currentChild : new TCTLTermListNode(factors); }
}


TCTLAbstractStateProperty AritmeticFactor() :
{
    TCTLAbstractStateProperty thisProp;
    Token trace = null;
    Token num;
}
{
    (
    [ LOOKAHEAD(2) trace = <IDENT> "." ] thisProp = Place() { return trace == null ? thisProp : new HyperLTLPathScopeNode(thisProp, trace.image); }
    | num = <NUM> { thisProp = new TCTLConstNode(Integer.parseInt(num.image)); }
    | "(" thisProp = AritmeticExpr() ")"
    )

    { return thisProp; }
}

TCTLAbstractStateProperty Place() :
{
    Token temp = null;
    Token place;
}
{
    temp = <IDENT> "." place = <IDENT> { return new TCTLPlaceNode(temp == null ? "" : temp.image, place.image); }
}
