#!/bin/sh

##Overwrite verifyta path:
#verifyta=/path/to/verifyta


if [ -z "$verifyta" ]; then
        #Search path for verifyta
	if [ -e /Applications/verifyta ]; then
	        export verifyta=/Applications/verifyta
	fi 
fi

if [ -f $HOME/.bash_profile ]; then
  . $HOME/.bash_profile
fi

if [ -f $HOME/.profile ]; then
  . $HOME/.profile
fi

if [ -z "$verifyta" ]; then
        #Search path for verifyta
        export verifyta=`which verifyta`
fi


( cd `dirname "$0"`; export verifytapn=$HOME/dev/verifytapn/src/verifytapn32; cd release-version; java -cp .:* TAPAAL)
