/* Generated By:JavaCC: Do not edit this line. TAPAALCTLQueryParserConstants.java */
package dk.aau.cs.TCTL.CTLParsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TAPAALCTLQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 1;
  /** RegularExpression Id. */
  int FALSE = 2;
  /** RegularExpression Id. */
  int DEADLOCK = 3;
  /** RegularExpression Id. */
  int EF = 4;
  /** RegularExpression Id. */
  int EG = 5;
  /** RegularExpression Id. */
  int E = 6;
  /** RegularExpression Id. */
  int A = 7;
  /** RegularExpression Id. */
  int U = 8;
  /** RegularExpression Id. */
  int EX = 9;
  /** RegularExpression Id. */
  int AF = 10;
  /** RegularExpression Id. */
  int AG = 11;
  /** RegularExpression Id. */
  int AX = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int MULT = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int IDENT = 20;
  /** RegularExpression Id. */
  int OP = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TRUE>",
    "<FALSE>",
    "<DEADLOCK>",
    "<EF>",
    "<EG>",
    "\"E\"",
    "\"A\"",
    "\"U\"",
    "\"EX\"",
    "<AF>",
    "<AG>",
    "\"AX\"",
    "<OR>",
    "<AND>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<NUM>",
    "<IDENT>",
    "<OP>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\".\"",
  };

}
